### PR TITLE
Use correct cast times for different spell ranks

### PR DESCRIPTION
**Pull request by Backupiseasy**
While I was working on integrating your library into Threat Plates, I added a cache for cast times based on unit level to account for different cast times because of spell ranks. It should work for casts and channeled spells, but I could not yet test channeled spells. 

Also, I changed FireToUnits for nameplates a bit, not using a for-loop to cycle through all nameplates, but using a hash table for faster access.

The first cast is still not correct and it does not factor in talents that change cast times, but I guess that is not easy to add, if at all.

### CODE REVIEW

**Comment by Backupiseasy** [comment]
Hm, maybe this is overly complicated. GetSpellInfo() does return the correct cast time based on rank as the spell IDs are different for each rank. So this should also work:

local function GetPlayerSpellCastTime(srcGUID, spellID, spellName, default_time)
    local name, rank, icon, castTime, minRange, maxRange, spellId = GetSpellInfo(spellID)

    if castTime then
        return castTime * 0.001
    end

    return nil
end

Not sure why this should not work ...

**Comment by d87** [comment]
Yeah that's really overcomplicating things.

Firstly, caching anything on players is a bad idea because of pushbacks, mobs don't have them.
Even if you gradually update spell's cast time to be the lowest registered for a given player,
then still mage casting Frostbolt rank 1 will fuck up the cast time of max rank casts.
Secondly, why even cache when you can just adjust based on level
There's only around 10 spells combined across all classes that change their cast times between ranks, and they all max out at around level 20 anyway.
I didn't do this before because pre level 20 pvp is really not a serious business, maybe i should tho
But for that many you can manually make a table with casttime breakpoints by level.

**Comment by d87** [comment]
And about GetSpellInfo(), it does return correct cast times, but there's no way to distinguish ranks by spell ID after blizzard removed them from combat log during stress test, Before, in beta, it was possible. Now I have to treat everything as max rank

**Comment by Backupiseasy** [comment]
Oh, for sure there's room for improvement. Regarding GetSpellInfo, the weird thing is that for Wrath you get different spell IDs for the different ranks, for Fireball that does not seem to be the case. I was not able to test that in detail, but it seems that way.

I used level just for faster access. Not every level has a rank, true, but I don't want to iterate through all entries to find the appropriate rank. It uses more memory, though.

Did not know that they max out at level 20, I guess it's fine then.

**Pull request closed without merging**
